spring:
  application:
    name: order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest

message:
  exchange: market
  queue:
    product: market.product
    payment: market.payment
